# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: voice_transcriber_development
  # Optional: add username/password if needed
  # username: your_local_username
  # password: your_local_password
  # host: localhost
  # port: 5432

test:
  <<: *default
  database: voice_transcriber_test
  # Optional: username/password/host/port as needed
  # username: your_local_username
  # password: your_local_password
  # host: localhost
  # port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
